-- SUPABASE_SCHEMA.sql
-- Run this in your Supabase SQL Editor to create the necessary tables for mirroring.
-- IMPORTANT: Copy the SQL content below and paste it into the SQL Editor (do not run the filename).

-- ---------------------------------------------------------
-- PART 1: ALL TABLES CREATION
-- ---------------------------------------------------------

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  uid TEXT,
  name TEXT,
  role TEXT,
  department TEXT,
  jobtitle TEXT,
  paymentbase TEXT,
  employeecategory TEXT,
  rate NUMERIC,
  status TEXT,
  lastactive TEXT,
  language TEXT,
  email TEXT,
  passwordhash TEXT,
  activesessions TEXT[],
  profilepicture TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Attendance Table
CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userid TEXT,
  date TEXT,
  checkintime TEXT,
  checkouttime TEXT,
  checkinlocation JSONB,
  checkoutlocation JSONB,
  checkinphoto TEXT,
  checkoutphoto TEXT,
  customerphoto TEXT,
  earnings NUMERIC DEFAULT 0,
  hoursworked NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'PRESENT',
  shipments INTEGER DEFAULT 0,
  odometerstart NUMERIC DEFAULT 0,
  odometerend NUMERIC DEFAULT 0,
  distancedriven NUMERIC DEFAULT 0,
  reviewneeded BOOLEAN DEFAULT FALSE,
  barcodes TEXT[],
  customervalue NUMERIC DEFAULT 0,
  erpvalue NUMERIC DEFAULT 0,
  valuedifference NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Messages Table
CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY,
  senderid TEXT,
  sendername TEXT,
  text TEXT,
  photourl TEXT,
  audiourl TEXT,
  timestamp TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Mismatches Table
CREATE TABLE IF NOT EXISTS mismatches (
  id TEXT PRIMARY KEY,
  userid TEXT,
  employeename TEXT,
  date TEXT,
  timestamp TEXT,
  barcodes TEXT[],
  customervalue NUMERIC,
  erpvalue NUMERIC,
  valuedifference NUMERIC,
  customerphoto TEXT,
  erpphoto TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Calls Table
CREATE TABLE IF NOT EXISTS calls (
  id TEXT PRIMARY KEY,
  userid TEXT,
  username TEXT,
  timestamp TEXT,
  type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Paydays Table
CREATE TABLE IF NOT EXISTS paydays (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userid TEXT,
  date TEXT,
  markedby TEXT,
  timestamp TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Salary History Table
CREATE TABLE IF NOT EXISTS salary_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userid TEXT,
  username TEXT,
  month TEXT,
  basesalary NUMERIC DEFAULT 0,
  shipmentearnings NUMERIC DEFAULT 0,
  totalearnings NUMERIC DEFAULT 0,
  totalhours NUMERIC DEFAULT 0,
  totalshipments INTEGER DEFAULT 0,
  totalmileage NUMERIC DEFAULT 0,
  dayspresent INTEGER DEFAULT 0,
  calculatedat TEXT,
  status TEXT DEFAULT 'PENDING',
  updatedat TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Broadcasts Table
CREATE TABLE IF NOT EXISTS broadcasts (
  id TEXT PRIMARY KEY,
  title TEXT,
  message TEXT,
  sentby TEXT,
  timestamp TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. Live Locations Table
CREATE TABLE IF NOT EXISTS live_locations (
  id TEXT PRIMARY KEY,
  userid TEXT,
  name TEXT,
  latitude NUMERIC,
  longitude NUMERIC,
  speed NUMERIC DEFAULT 0,
  accuracy NUMERIC DEFAULT 0,
  lastupdate TEXT,
  status TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. Location Logs Table (for path history and idle detection)
CREATE TABLE IF NOT EXISTS location_logs (
  id TEXT PRIMARY KEY,
  userid TEXT,
  latitude NUMERIC,
  longitude NUMERIC,
  timestamp TEXT,
  speed NUMERIC,
  accuracy NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 11. Walkie Talkie Table (for real-time push-to-talk)
CREATE TABLE IF NOT EXISTS walkie_talkie (
  id TEXT PRIMARY KEY,
  userId TEXT,
  userName TEXT,
  audioUrl TEXT,
  duration NUMERIC,
  timestamp TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 12. Ad-Hoc Jobs Table
CREATE TABLE IF NOT EXISTS ad_hoc_jobs (
  id TEXT PRIMARY KEY,
  userid TEXT,
  employeename TEXT,
  date TEXT,
  vehicletype TEXT,
  starttime TEXT,
  endtime TEXT,
  totalhours NUMERIC,
  value NUMERIC,
  status TEXT DEFAULT 'PENDING',
  timestamp TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 13. App Updates Table
CREATE TABLE IF NOT EXISTS app_updates (
  id TEXT PRIMARY KEY,
  version TEXT,
  message TEXT,
  url TEXT,
  ismandatory BOOLEAN DEFAULT FALSE,
  releasedby TEXT,
  timestamp TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 14. Cash Reports Table
CREATE TABLE IF NOT EXISTS cash_reports (
  id TEXT PRIMARY KEY,
  userid TEXT,
  username TEXT,
  date TEXT,
  timestamp TEXT,
  denominations JSONB,
  onlinecash NUMERIC DEFAULT 0,
  valuemismatch NUMERIC DEFAULT 0,
  totalamount NUMERIC DEFAULT 0,
  totalnotes INTEGER DEFAULT 0,
  status TEXT DEFAULT 'SUBMITTED',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ---------------------------------------------------------
-- PART 2: ENSURE COLUMNS EXIST (For Upgrade Safety)
-- ---------------------------------------------------------
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mismatches' AND column_name='customerphoto') THEN
    ALTER TABLE mismatches ADD COLUMN customerphoto TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='mismatches' AND column_name='erpphoto') THEN
    ALTER TABLE mismatches ADD COLUMN erpphoto TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='employeecategory') THEN
    ALTER TABLE users ADD COLUMN employeecategory TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='customerphoto') THEN
    ALTER TABLE attendance ADD COLUMN customerphoto TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='odometerstart') THEN
    ALTER TABLE attendance ADD COLUMN odometerstart NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='odometerend') THEN
    ALTER TABLE attendance ADD COLUMN odometerend NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='distancedriven') THEN
    ALTER TABLE attendance ADD COLUMN distancedriven NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='reviewneeded') THEN
    ALTER TABLE attendance ADD COLUMN reviewneeded BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='customervalue') THEN
    ALTER TABLE attendance ADD COLUMN customervalue NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='erpvalue') THEN
    ALTER TABLE attendance ADD COLUMN erpvalue NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='valuedifference') THEN
    ALTER TABLE attendance ADD COLUMN valuedifference NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='barcodes') THEN
    ALTER TABLE attendance ADD COLUMN barcodes TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='ad_hoc_jobs' AND column_name='status') THEN
    ALTER TABLE ad_hoc_jobs ADD COLUMN status TEXT DEFAULT 'PENDING';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='live_locations' AND column_name='speed') THEN
    ALTER TABLE live_locations ADD COLUMN speed NUMERIC DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='live_locations' AND column_name='accuracy') THEN
    ALTER TABLE live_locations ADD COLUMN accuracy NUMERIC DEFAULT 0;
  END IF;
END $$;


-- ---------------------------------------------------------
-- PART 3: ENABLE RLS & ADD POLICIES
-- ---------------------------------------------------------
DO $$ 
DECLARE
  t text;
  pol record;
  tables text[] := ARRAY['users', 'attendance', 'messages', 'mismatches', 'calls', 'paydays', 'salary_history', 'broadcasts', 'live_locations', 'location_logs', 'walkie_talkie', 'ad_hoc_jobs', 'app_updates', 'cash_reports'];
BEGIN
  FOREACH t IN ARRAY tables LOOP
    -- Enable RLS
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    
    -- Aggressively drop ALL existing policies for these tables to prevent conflicts
    FOR pol IN (SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = t) LOOP
      EXECUTE format('DROP POLICY %I ON %I', pol.policyname, t);
    END LOOP;
    
    -- Create fresh policy to allow all operations for anon (essential for sync mirroring in this app)
    EXECUTE format('CREATE POLICY "Allow All for Sync" ON %I FOR ALL USING (true) WITH CHECK (true)', t);
  END LOOP;
END $$;
